apiVersion: v1
kind: Service
metadata:
  name: drd-vpc-agent-service
  annotations:
    meta.helm.sh/release-name: "{{ .Release.name }}"
spec:
  selector:
    app: drd-vpc-agent-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
