version: "3.9"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    image: fluent/fluentd:v1.12-debian-1
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - mynetwork

  server:
    image: public.ecr.aws/y9s1f3r5/drdroid/drd-vpc-agent:latest
    command: ./start-server.sh
    ports:
      - 8080:8080
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - DRD_CLOUD_API_TOKEN=${DRD_CLOUD_API_TOKEN}
      - DRD_CLOUD_API_HOST=${DRD_CLOUD_API_HOST}
    depends_on:
      - redis
      - fluentd
    volumes:
      - ./credentials/secrets.yaml:/code/credentials/secrets.yaml
    logging:
      driver: fluentd
      options:
        fluentd-address: docker.for.mac.localhost:24224
        tag: "server"
        fluentd-async: "true"
    networks:
      - mynetwork

  celery_worker:
    image: public.ecr.aws/y9s1f3r5/drdroid/drd-vpc-agent:latest
    command: ./start-celery-worker.sh
    environment:
      - "DJANGO_DEBUG=True"
      - "CELERY_BROKER_URL=redis://redis:6379/0"
      - "CELERY_RESULT_BACKEND=redis://redis:6379/0"
      - "REDIS_URL=redis://redis:6379/0"
      - DRD_CLOUD_API_TOKEN=${DRD_CLOUD_API_TOKEN}
      - DRD_CLOUD_API_HOST=${DRD_CLOUD_API_HOST}
    depends_on:
      - redis
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: docker.for.mac.localhost:24224
        tag: "celery_worker"
        fluentd-async: "true"
    networks:
      - mynetwork

networks:
  mynetwork:
