apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drdroid-k8s-cluster-role
rules:
  # Core API group
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - events
      - configmaps
      - secrets
      - namespaces
      - nodes
      - persistentvolumes
      - persistentvolumeclaims
    verbs: ["get", "list", "watch"]

  # Extensions to core resources
  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get"]

  # Apps API group
  - apiGroups: ["apps"]
    resources:
      - deployments
      - statefulsets
      - daemonsets
      - replicasets
    verbs: 
      - "get"
      - "list"
      - "watch"
      {{- if .Values.writeAccess.enabled }}
      - "patch"
      - "update"
      - "delete"
      {{- end }}

  # Batch jobs
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # Networking
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs: ["get", "list", "watch"]

  # RBAC (if monitoring permissions/roles)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
      - clusterroles
      - clusterrolebindings
    verbs: ["get", "list", "watch"]

  # API discovery
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]

  # Node metrics (optional, depending on use case)
  - apiGroups: ["metrics.k8s.io"]
    resources:
      - nodes
      - pods
    verbs: ["get", "list", "watch"]

  # Storage
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs: ["get", "list", "watch"]

  # Custom Resource Definitions (if using CRDs)
  - apiGroups: ["apiextensions.k8s.io"]
    resources:
      - customresourcedefinitions
    verbs: ["get", "list", "watch"]
