apiVersion: v1
kind: Secret
metadata:
  name: drd-cloud-secret
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DRD_CLOUD_API_TOKEN: {{ .Values.global.DRD_CLOUD_API_TOKEN | quote }}
