apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drd-vpc-agent-otterize-role
  namespace: otterize-system
rules:
  - apiGroups: [""]
    resources:
      - pods/portforward
    verbs: ["create"]

