apiVersion: v2
name: drd-vpc-agent
description: Celery-only deployment
version: 0.1.0

dependencies:
  - name: celery-beat
    version: 0.1.0
    repository: "file://charts/celery_beat"
  - name: celery-worker
    version: 0.1.0
    repository: "file://charts/celery_worker"
  - name: redis
    version: 0.1.0
    repository: "file://charts/redis"