global:
  DRD_CLOUD_API_TOKEN: ""
  DRD_CLOUD_API_HOST: "https://agent-api.drdroid.io"
  NATIVE_KUBERNETES_API_MODE: "true"

restartCron:
  enabled: true
  schedule: "0 0 * * *"  # every day at 00:00 UTC

celery-beat:
  image:
    repository: drdroidlab/drd-vpc-agent
    tag: dual-queue-v1
    pullPolicy: Always

celery-worker:
  image:
    repository: drdroidlab/drd-vpc-agent
    tag: dual-queue-v1
    pullPolicy: Always

redis:
  image: redis:7.2