global:
  DRD_CLOUD_API_TOKEN: ""
  DRD_CLOUD_API_HOST: "https://agent-api.drdroid.io"
  NATIVE_KUBERNETES_API_MODE: "true"

  # Global node scheduling configuration
  # Applied to all services (redis, celery-beat, celery-worker)
  # Example nodeSelector:
  # nodeSelector:
  #   "worker-type": "aux-pool"
  #   "kubernetes.io/os": "linux"
  nodeSelector: {}

  # Example tolerations:
  # tolerations:
  #   - key: "dedicated"
  #     operator: "Equal"
  #     value: "infra"
  #     effect: "NoSchedule"
  tolerations: []

# Network Mapper Configuration
# Controls whether the network mapper components are deployed
# The network mapper provides service topology visibility and network insights
# Default: enabled (recommended for full functionality)
networkMapper:
  enabled: false

# Write Access Configuration  
# Controls whether deployed pods get write access to the cluster
# When disabled, pods run in read-only mode for enhanced security
# Default: enabled (required for full agent functionality)
writeAccess:
  enabled: false

restartCron:
  enabled: true
  schedule: "0 0 * * *"  # every day at 00:00 UTC

celery-beat:
  image:
    repository: drdroidlab/drd-vpc-agent
    tag: latest
    pullPolicy: Always

celery-worker:
  image:
    repository: drdroidlab/drd-vpc-agent
    tag: latest
    pullPolicy: Always

redis:
  image: redis:7.2