apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drd-vpc-agent-binding
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
subjects:
  - kind: ServiceAccount
    name: drd-vpc-agent
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: drdroid-k8s-cluster-role
  apiGroup: rbac.authorization.k8s.io 