apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mcpServer.service.name }}
  labels:
    {{- include "drd-vpc-agent-mcp.labels" . | nindent 4 }}
    component: mcp-server
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
spec:
  type: {{ .Values.mcpServer.service.type }}
  ports:
    - port: {{ .Values.mcpServer.service.port }}
      targetPort: {{ .Values.mcpServer.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "drd-vpc-agent-mcp.selectorLabels" . | nindent 4 }}
    component: mcp-server 